### ISSUE TITLE
Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by kfiven** [flatpak/flatpak-builder-tools#299] opened 2022-07-05 15:41 UTC
### flatpak-builder version

1.2.2

### Linux distribution and version

Ubuntu 20.04

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### Source repository URL

https://github.com/kfiven/cinny-desktop

### Description

Running `flatpak-node-generator npm -r cinny/package-lock.json -o node-sources.json` gives
```
Traceback (most recent call last):
Found 1 lockfiles.
  File "/opt/pipx_bin/flatpak-node-generator", line [8](https://github.com/kfiven/cinny-desktop/runs/7199286241?check_suite_focus=true#step:10:9), in <module>
    sys.exit(main())
  File "/opt/pipx/venvs/flatpak-node-generator/lib/python3.10/site-packages/flatpak_node_generator/main.py", line 277, in main
    asyncio.run(_async_main())
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/asyncio/runners.py", line 44, in run
Reading packages from lockfiles...
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/pipx/venvs/flatpak-node-generator/lib/python3.10/site-packages/flatpak_node_generator/main.py", line 1[9](https://github.com/kfiven/cinny-desktop/runs/7199286241?check_suite_focus=true#step:10:10)8, in _async_main
    packages.update(lockfile_provider.process_lockfile(lockfile))
  File "/opt/pipx/venvs/flatpak-node-generator/lib/python3.[10](https://github.com/kfiven/cinny-desktop/runs/7199286241?check_suite_focus=true#step:10:11)/site-packages/flatpak_node_generator/providers/npm.py", line 79, in process_lockfile
    yield from self.process_dependencies(lockfile, data.get('dependencies', {}))
  File "/opt/pipx/venvs/flatpak-node-generator/lib/python3.10/site-packages/flatpak_node_generator/providers/npm.py", line 66, in process_dependencies
    source = ResolvedSource(resolved=info['resolved'], integrity=integrity)
KeyError: 'resolved'
Error: Process completed with exit code 1.
```

**Comment by gasinvein** [comment] 2022-07-05 19:15
Duplicate of #295

**Closed by gasinvein** 2022-07-05 19:15 UTC
Labels: bug, npm, node
