### ISSUE TITLE
pip generator: should it use ${FLATPAK_DEST}/bin/pip3 instead of pip3

### ISSUE THREAD

**Issue by jonathon-love** [flatpak/flatpak-builder-tools#16] opened 2018-02-25 22:01 UTC
hi,

i'm using the pip generator, and it generates pip install commands like this:

```
pip3 install --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} name
```

however, if you're using pip, you would presumably already be including a python module? by using *just* `pip3`, the build uses the system python version, which may not match the python version used in the package.

in my case, i have to change all the pip3's to:

```
${FLATPAK_DEST}/bin/pip3
```

should the pip generator do this too? or should i be doing this a different way?

with thanks

**Comment by TingPing** [comment] 2018-02-25 23:43
That wouldn't make any sense. If the package installs `/app/bin/pip3` it will be picked up first in `PATH`. In most packages which do not install `/app/bin/pip3` then `$FLATPAK_DEST/bin/pip3` will just fail because it doesn't exist.

**Comment by jonathon-love** [comment] 2018-02-26 02:31
hi,

> If the package installs /app/bin/pip3 it will be picked up first in $PATH

this isn't how it works on my machine. pip3 *is* installed to `files/bin/pip3`, but if i add a `pip3 --version` into build commands it says:

```
pip 8.1.2 from /usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg (python 3.5)
```

the `files/bin/pip3` isn't being given preference.

> In most packages which do not install /app/bin/pip3 then $FLATPAK_DEST/bin/pip3 will just fail because it doesn't exist.

this is true, but would you ever use packages from pypi without using python?

kind regards

jonathon

**Comment by TingPing** [comment] 2018-02-26 13:27
> this is true, but would you ever use packages from pypi without using python?

Python is in the runtime, or else `pip3` wouldn't work at all in the first place.

> this isn't how it works on my machine.

Can't reproduce:

```json
    {
      "name": "fakepip",
      "buildsystem": "simple",
      "build-commands": [
        "install pip3 /app/bin"
      ],
      "sources": [
        {
          "type": "script",
          "commands": ["echo I am the local pip3"],
          "dest-filename": "pip3"
        }
      ]
    },
    {
      "name": "piptest",
      "buildsystem": "simple",
      "build-commands": [
        "pip3 --version"
      ]
    }
```

output:

```
Running: pip3 --version
I am the local pip3
```

**Comment by jonathon-love** [comment] 2018-02-26 13:49
hmm, well i guess we're in a *can't reproduce infinite loop*. :/

```
{
    "app-id": "org.flatpak.Hello",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "1.6",
    "sdk": "org.freedesktop.Sdk",
    "command": "hello.sh",
    "modules": [
        {
          "name": "fakepip",
          "buildsystem": "simple",
          "build-commands": [
            "install pip3 /app/bin"
          ],
          "sources": [
            {
              "type": "script",
              "commands": ["echo I am the local pip3"],
              "dest-filename": "pip3"
            }
          ]
        },
        {
          "name": "piptest",
          "buildsystem": "simple",
          "build-commands": [
            "pip3 --version"
          ]
        }
    ]
}
```

output:

```
$ flatpak-builder app-dir org.flatpak.Hello.json 
Downloading sources
Starting build of org.flatpak.Hello
Cache miss, checking out last cache hit
========================================================================
Building module fakepip in /home/jonathon/Documents/fpt/.flatpak-builder/build/fakepip-1
========================================================================
Running: install pip3 /app/bin
Committing stage build-fakepip to cache
========================================================================
Building module piptest in /home/jonathon/Documents/fpt/.flatpak-builder/build/piptest-1
========================================================================
Running: pip3 --version
pip 8.1.2 from /usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg (python 3.5)
```

**Comment by TingPing** [comment] 2018-02-26 13:51
Maybe the `flatpak` version is relevant. I'll presume you are on an Ubuntu and you should grab the PPA which is up to date: https://flatpak.org/getting.html

**Comment by jonathon-love** [comment] 2018-02-26 13:55
i'm using the latest version from the alexlarsson PPA

**Comment by TingPing** [comment] 2018-02-26 13:59
Hmm well this is my path:

```
Running: echo $PATH
/run/ccache/bin:/app/bin:/usr/bin
```

Will need to figure out where that is set.

**Comment by TingPing** [comment] 2018-02-26 14:01
BTW is Python 3.5 really too old for your needs?

**Comment by jonathon-love** [comment] 2018-02-26 14:03
my path is

```
Running: echo $PATH
/app/bin:/usr/bin
```

which doesn't make a heap of sense to me, because i feel like it should be able to find the local pip

**Comment by jonathon-love** [comment] 2018-02-26 14:04
> BTW is Python 3.5 really too old for your needs?

no, that's fine. i didn't realise that 3.5 shipped as part of the runtime. i assumed i would need to include a version of python in the flatpak.

**Comment by TingPing** [comment] 2018-02-26 14:05
Well anyway I'll be closing this since it doesn't make sense. If it continues to be a problem I suppose report it against flatpak/flatpak but with `$PATH` is correct and doesn't work you must have angered the unix gods or something.

**Closed by TingPing** 2018-02-26 14:05 UTC
