### ISSUE TITLE
flatpak-pip-generator doesn't consider python_version

### ISSUE THREAD

**Issue by faveoled** [flatpak/flatpak-builder-tools#389] opened 2024-01-28 12:45 UTC
### flatpak-builder version

1.2.2

### Linux distribution and version

Ubuntu 22.04.3

### Affected flatpak-builder tool

pip/flatpak-pip-generator

### Description

Generates two versions in output when requirements contains python_version comparison:
```
Flask==2.3.*; python_version > '3.7'
Flask==2.2.*; python_version <= '3.7'
```
[requirements_test.txt](https://github.com/flatpak/flatpak-builder-tools/files/14076058/requirements_test.txt)

[python3-requirements_test.json](https://github.com/flatpak/flatpak-builder-tools/files/14076057/python3-requirements_test.json)
Also seems to fail with this:
```
pywinpty==2.0.*; sys_platform=="win32"
```

**Comment by bbhtt** [comment] 2024-01-28 12:46
Dupe of https://github.com/flatpak/flatpak-builder-tools/issues/365

**Closed** 2024-01-28 12:47 UTC
Labels: bug
