### ISSUE TITLE
pip-generator tries to build lxml instead of just downloading the package

### ISSUE THREAD

**Issue by ptomato** [flatpak/flatpak-builder-tools#13] opened 2018-01-25 18:04 UTC
When I try to generate a manifest for lxml, I get this:
```
$ ./flatpak-pip-generator lxml
Collecting lxml
  Using cached lxml-4.1.1.tar.gz
  Saved /tmp/pip-generator-lxml-h78x83nm/lxml-4.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Building lxml version 4.1.1.
    Building without Cython.
    ERROR: b'ERROR: /usr/bin/xslt-config should not be used, use an alternative such as pkg-config\n'
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt --should-not-have-used-/usr/bin/xslt-config
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_4tafq7b/lxml/setup.py", line 240, in <module>
        **setup_extra_options()
      File "/tmp/pip-build-_4tafq7b/lxml/setup.py", line 150, in setup_extra_options
        STATIC_CFLAGS, STATIC_BINARIES)
      File "/tmp/pip-build-_4tafq7b/lxml/setupinfo.py", line 115, in ext_modules
        versions_ok |= check_min_version(lib_versions[1], (1, 1, 23), 'libxslt')
      File "/tmp/pip-build-_4tafq7b/lxml/setupinfo.py", line 378, in check_min_version
        version = tuple(map(int, version.split('.')[:3]))
    ValueError: invalid literal for int() with base 10: '--should-not-have-used-/usr/bin/xslt-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_4tafq7b/lxml/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "./flatpak-pip-generator", line 52, in <module>
    ] + opts.packages, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pip3', 'download', '--dest', '/tmp/pip-generator-lxml-h78x83nm', '--no-binary', ':all:', 'lxml']' returned non-zero exit status 1
```
Looks like there's something special about the lxml package that causes it to try to build the package instead of just downloading it.

**Comment by TingPing** [comment] 2018-01-25 18:27
So we cannot just download the binary as we all know that is broken on many levels:

- ABI is a thing and Python packages have no knowledge of them
- Flatpak targets multiple arches and few Python packages have binaries for aarch64, arm, etc

On the slightly positive side of things I do have a patch to fix `lxml` building: https://github.com/GNOME/gnome-builder/blob/master/build-aux/flatpak/lxml-Fix-getting-lib-version-when-using-pkg-config.patch

**Comment by ptomato** [comment] 2018-01-26 00:01
So maybe `flatpak-pip-generator` should abort if you ask it to download `lxml` since that package is broken, and point you to what to do instead?

**Comment by TingPing** [comment] 2018-01-26 00:35
Perhaps, there will be an ever growing list of broken packages though that is just unavoidable.

**Comment by TingPing** [comment] 2018-01-26 00:36
We could try to be extra smart and add the patched build ourselves...

**Comment by TingPing** [comment] 2018-01-26 00:40
Also looks like [lxml](https://github.com/lxml/lxml) is still actively maintained so I'll look into sending the fix their way.

**Comment by TingPing** [comment] 2018-01-26 20:51
https://github.com/lxml/lxml/pull/259

**Comment by scoder** [comment] 2018-01-26 21:02
For x86 and x64 Linux, the lxml wheels should be just fine (they are [manylinux](https://www.python.org/dev/peps/pep-0513/) wheels). All other architectures would still require a build. I agree that `pkg-config` is generally the way to go, although I don't understand the problem here.

**Comment by TingPing** [comment] 2018-01-26 21:10
> All other architectures would still require a build. 

Right, which is true for most packages and makes even attempting to download binary builds a moot-point.

> I agree that pkg-config is generally the way to go, although I don't understand the problem here.

`xml2-config` and `xslt-config` just aren't usable in the fdo runtime for whatever reason and have to be worked around.

**Comment by TingPing** [comment] 2018-07-10 09:34
I got this fixed upstream: https://github.com/lxml/lxml/pull/259

It will require us setting an env var once the new release is out.

**Comment by TingPing** [comment] 2018-08-09 22:50
So this has made it into a release so we can special case setting those env vars.

Also fdo 18.xx avoids this issue in the first place and will just work.

**Comment by danyeaw** [comment] 2019-10-24 02:11
This issue seems to be resolved by your PR upstream, I can no longer reproduce.

**Closed** 2019-10-24 04:16 UTC
Labels: pip
