### ISSUE TITLE
Replace source distribution by multiple wheels for arch compatibility.

### ISSUE THREAD

**Issue by real-yfprojects** [flatpak/flatpak-builder-tools#297] opened 2022-06-29 19:01 UTC
### flatpak-builder version

1.0.10

### Linux distribution and version

Ubuntu 20.04

### Affected flatpak-builder tool

pip/flatpak-pip-generator

### Description

When generating a dependency file for the python package `cryptography` from pypi.org, the `flatpak-pip-generator` recognised that the package only supplies platform dependent wheel distributions and therefore includes the source distribution . However the source distribution can only be build by compiling complicated rust dependencies and building the app with flatpak-builder fails therefore. I solved this by replacing the source distribution with all the different wheel packages available so that the right one is always available. Why can't `flatpak-pip-generator` do something similar?

PS: Which wheel distributions do I actually need for building the flatpak on aarch64 and x86?

**Comment by hfiguiere** [comment] 2022-06-29 19:31
Dupe of #296

**Closed by hfiguiere** 2022-06-29 19:31 UTC
Labels: bug

**Comment by real-yfprojects** [comment] 2022-06-29 19:40
Oh this was due to a github bug showing a HTTP 404 error on opening issue #296 although the operation succeeded in the background.
