### ISSUE TITLE
flatpak script doesn't work with large package lists

### ISSUE THREAD

**Issue by radiodee1** [flatpak/flatpak-builder-tools#307] opened 2022-07-15 13:48 UTC
### flatpak-builder version

1.2.2

### Linux distribution and version

Ubuntu 22.04

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### flatpak-builder tool cli args

 npm --xdg-layout ../package-lock.json

### Source repository URL

Private

### Description

I get the following when using flatpak-node-generator.py . I have 2613 packages. The program gets to 2608 and then exits. What should I do?

        Reading packages from lockfiles...
        2613 packages read.
        Generating packages [2608/2613] forever-agent @ 0.2.0Task exception was never retrieved                                                                                                       
        future: <Task finished name='Task-290' coro=<GeneratorProgress._generate() done, defined at /home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py:1715> exception=AssertionError('global versions available are 1.0.0, 0.1.5, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 3.0.0, 3.0.1, 3.0.2, 4.0.0, 4.0.1, 4.1.0, 4.2.0, 4.2.1, 4.3.0, 4.3.1, 4.3.2, 4.4.0, not https://github.com/component/global/archive/v2.0.1.tar.gz')>
        Traceback (most recent call last):
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1717, in _generate
            await self.module_provider.generate_package(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1371, in generate_package
            source = await self.resolve_source(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1346, in resolve_source
            assert package.version in versions, \
        AssertionError: global versions available are 1.0.0, 0.1.5, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 3.0.0, 3.0.1, 3.0.2, 4.0.0, 4.0.1, 4.1.0, 4.2.0, 4.2.1, 4.3.0, 4.3.1, 4.3.2, 4.4.0, not https://github.com/component/global/archive/v2.0.1.tar.gz
        Task exception was never retrieved
        future: <Task finished name='Task-37' coro=<GeneratorProgress._generate() done, defined at /home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py:1715> exception=AssertionError('emitter versions available are 0.0.2, 0.0.1, 0.0.3, 0.0.4, 0.0.5, not http://github.com/component/emitter/archive/1.0.1.tar.gz')>
        Traceback (most recent call last):
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1717, in _generate
            await self.module_provider.generate_package(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1371, in generate_package
            source = await self.resolve_source(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1346, in resolve_source
            assert package.version in versions, \
        AssertionError: emitter versions available are 0.0.2, 0.0.1, 0.0.3, 0.0.4, 0.0.5, not http://github.com/component/emitter/archive/1.0.1.tar.gz
        Task exception was never retrieved
        future: <Task finished name='Task-2224' coro=<GeneratorProgress._generate() done, defined at /home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py:1715> exception=AssertionError('https://registry.npmjs.org/@vue%2fvue-loader-v15 returned an invalid package index')>
        Traceback (most recent call last):
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1717, in _generate
            await self.module_provider.generate_package(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1371, in generate_package
            source = await self.resolve_source(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1332, in resolve_source
            assert 'versions' in data, f'{data_url} returned an invalid package index'
        AssertionError: https://registry.npmjs.org/@vue%2fvue-loader-v15 returned an invalid package index
        Task exception was never retrieved
        future: <Task finished name='Task-1869' coro=<GeneratorProgress._generate() done, defined at /home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py:1715> exception=AssertionError('emitter versions available are 0.0.2, 0.0.1, 0.0.3, 0.0.4, 0.0.5, not http://github.com/component/emitter/archive/1.0.1.tar.gz')>
        Traceback (most recent call last):
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1717, in _generate
            await self.module_provider.generate_package(package
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1371, in generate_package
            source = await self.resolve_source(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1346, in resolve_source
            assert package.version in versions, \
        AssertionError: emitter versions available are 0.0.2, 0.0.1, 0.0.3, 0.0.4, 0.0.5, not http://github.com/component/emitter/archive/1.0.1.tar.gz
        Task exception was never retrieved
        future: <Task finished name='Task-1465' coro=<GeneratorProgress._generate() done, defined at /home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py:1715> exception=AssertionError('xmlhttprequest versions available are 1.0.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.2, 1.5.0, 1.6.0, 1.7.0, 1.8.0, not https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz')>
        Traceback (most recent call last):
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1717, in _generate
            await self.module_provider.generate_package(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1371, in generate_package
            source = await self.resolve_source(package)
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1346, in resolve_source
            assert package.version in versions, \
        AssertionError: xmlhttprequest versions available are 1.0.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.2, 1.5.0, 1.6.0, 1.7.0, 1.8.0, not https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz

        Traceback (most recent call last):
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1929, in <module>
            asyncio.run(main())
          File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
            return loop.run_until_complete(main)
          File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
            return future.result()
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1885, in main
            with provider_factory.create_module_provider(gen, special) as module_provider:
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1282, in __exit__
            self._finalize()
          File "/home/dave/workspace/electron-gpt/flatpak/tools/node/flatpak-node-generator.py", line 1397, in _finalize
            index = async_index.result()
        asyncio.exceptions.InvalidStateError: Result is not set.

)

**Comment by gasinvein** [comment] 2022-07-15 13:53
"Source repository URL" form field was for the source of the app you're trying to build, where the `package-lock.json` file comes from.

**Comment by radiodee1** [comment] 2022-07-15 18:00
I did not know about the "Source repository URL". the url for that project is private for the time being.

**Comment by gasinvein** [comment] 2022-07-15 18:40
Can you share at least the lockfile (all of them if there are several)? It would be easier to debug if we could reproduce it.
In any case, from the error alone it looks like a duplicate of #145

**Comment by radiodee1** [comment] 2022-07-15 18:52
[package-lock.json.txt](https://github.com/flatpak/flatpak-builder-tools/files/9123264/package-lock.json.txt)

I have tried to include the package-lock.json file here.

**Comment by gasinvein** [comment] 2022-07-15 19:02
Thanks. Yes, this is duplicate of #145

**Closed by gasinvein** 2022-07-15 19:02 UTC
Labels: bug, npm, node
