### ISSUE TITLE
Build failure with git version of Relm4

### ISSUE THREAD

**Issue by azymohliad** [flatpak/flatpak-builder-tools#352] opened 2023-03-01 20:38 UTC
### flatpak-builder version

1.2.3

### Linux distribution and version

ArchLinux

### Affected flatpak-builder tool

cargo/flatpak-cargo-generator.py

### Source repository URL

https://github.com/azymohliad/watchmate

### Flatpak-builder manifest URL

https://github.com/flathub/io.gitlab.azymohliad.WatchMate/blob/release/v0.4.3/io.gitlab.azymohliad.WatchMate.yml

### Description

Hi! I'm not sure if it's a flatpak-builder-tools issue, but this is my best guess so far. Apologies if it's incorrect.

I get a cryptic error from [Flathub CI build](https://buildbot.flathub.org/#/builders/7/builds/3159), which I can also reproduce locally with the version of build manifest that uses flatpak-cargo-generator:

```
error: failed to get `anyhow` as a dependency of package `watchmate v0.4.3 (/run/build/watchmate/watchmate)`
Caused by:
  failed to load source for dependency `anyhow`
Caused by:
  Unable to update registry `crates-io`
Caused by:
  failed to update replaced source registry `crates-io`
Caused by:
  failed to parse manifest at `/run/build/watchmate/cargo/vendor/relm4/Cargo.toml`
Caused by:
  error inheriting `version` from workspace root manifest's `workspace.package.version`
Caused by:
  `workspace.package.version` was not defined
FB: host_command_exited_cb 2684940 25856 
```

After some experiments I narrowed the cause down to the source of Relm4 dependency. If I use crates.io version with the following declaration in `Cargo.toml` then everything works:

```
relm4 = { version = "v0.5.0", features = ["libadwaita", "gnome_43"] }
relm4-components = { version = "v0.5.0" }
```

But if use git version from exactly the same commit, then I get the error as above.

```
relm4 = { git = "https://github.com/Relm4/relm4", tag = "v0.5.0", features = ["libadwaita", "gnome_43"] }
relm4-components = { git = "https://github.com/Relm4/relm4", tag = "v0.5.0" }
```

Both work fine with [the version of Flatpak manifest that doesn't use flatpak-cargo-generator](https://github.com/azymohliad/watchmate/blob/main/flatpak/io.gitlab.azymohliad.WatchMate.yml).

**Comment by hfiguiere** [comment] 2023-03-01 20:40
using git version is always a source of problems.

**Comment by gasinvein** [comment] 2023-03-01 23:08
It looks like the error happens because of inheriting values from workspace in some of the dependencies.

**Comment by gasinvein** [comment] 2023-03-01 23:08
Duplicate of #348

**Closed by gasinvein** 2023-03-01 23:08 UTC
Labels: bug

**Comment by azymohliad** [comment] 2023-03-02 06:49
Oh, thanks! Sorry for the duplicate
